<?php
declare(strict_types=1);

namespace GH\Core\Pipeline;

/**
 * Persistence for saved pipelines. Stored as a wp_options list under the
 * key 'gh_pipelines' via the existing gh_option_list_* helpers, matching
 * how brand/templates/campaigns/jobs already serialize.
 *
 * Schema (one row):
 *   {
 *     id          : 'pl_xxxx',
 *     name        : string,
 *     steps       : [ {kind, ref_id, params, note?}, ... ],
 *     meta        : { ... free form ... },
 *     created_at  : mysql datetime,
 *     updated_at  : mysql datetime,
 *   }
 *
 * Pipelines are addressable by id from Job params, so a scheduled
 * source.import job carries its pipeline reference and the executor
 * always loads the current version at run time (never a snapshot).
 */
final class PipelineRepository
{
    public const OPTION_KEY = 'gh_pipelines';
    private const ID_PREFIX = 'pl_';

    public function find(string $id): ?Pipeline
    {
        if (! function_exists('gh_option_list_find')) {
            return null;
        }
        $row = \gh_option_list_find(self::OPTION_KEY, $id);
        return $row ? self::hydrate($row) : null;
    }

    /** @return Pipeline[] */
    public function all(): array
    {
        if (! function_exists('gh_option_list_all')) {
            return [];
        }
        $rows = \gh_option_list_all(self::OPTION_KEY);
        return array_map([self::class, 'hydrate'], $rows);
    }

    /**
     * Persist a pipeline (create or update). Returns the stored id.
     * If $pipeline->id is empty, a new id is generated by the option store.
     */
    public function save(Pipeline $pipeline): string
    {
        if (! function_exists('gh_option_list_upsert')) {
            throw new \RuntimeException('gh_option_list_upsert not available — legacy core helpers not loaded.');
        }
        $payload = self::dehydrate($pipeline);
        $stored = \gh_option_list_upsert(
            self::OPTION_KEY,
            $payload,
            'id',
            self::ID_PREFIX,
        );
        return (string) ($stored['id'] ?? '');
    }

    public function delete(string $id): bool
    {
        if (! function_exists('gh_option_list_remove')) {
            return false;
        }
        return (bool) \gh_option_list_remove(self::OPTION_KEY, $id);
    }

    private static function hydrate(array $row): Pipeline
    {
        $steps = [];
        foreach (($row['steps'] ?? []) as $s) {
            $kind = PipelineStepKind::tryFrom((string) ($s['kind'] ?? '')) ?? PipelineStepKind::Operation;
            $steps[] = new PipelineStep(
                kind: $kind,
                refId: (string) ($s['ref_id'] ?? ''),
                params: (array) ($s['params'] ?? []),
                note: isset($s['note']) ? (string) $s['note'] : null,
            );
        }
        return new Pipeline(
            id: (string) ($row['id'] ?? ''),
            name: (string) ($row['name'] ?? ''),
            steps: $steps,
            meta: (array) ($row['meta'] ?? []),
        );
    }

    private static function dehydrate(Pipeline $p): array
    {
        return [
            'id'    => $p->id,
            'name'  => $p->name,
            'steps' => array_map(static fn(PipelineStep $s): array => [
                'kind'   => $s->kind->value,
                'ref_id' => $s->refId,
                'params' => $s->params,
                'note'   => $s->note,
            ], $p->steps),
            'meta'  => $p->meta,
        ];
    }
}
