<?php
/**
 * Hive Sync host bridge.
 *
 * Binds the Hive Sync host adapter contract (filters/actions defined in
 * the Hive Sync plugin) to the Golden Hive functions that already exist.
 * Purely additive: if Hive Sync is not installed nothing here ever runs;
 * if Hive Sync is installed but nothing calls the helpers, this file is
 * inert.
 *
 * Bound (phase 2):
 *   - hive_sync/host/taxonomy/resolve   → WP get_term_by + rp_cm_create_category
 *   - hive_sync/host/conflict/record    → gh_conflict_record_source
 *   - hive_sync/host/conflict/resolve   → gh_conflict_resolve
 *   - hive_sync/host/selection/resolve  → gh_filter_product_ids (Filter mode)
 *
 * Deferred to phase 3 (need concrete data shape locked):
 *   - hive_sync/host/media/preimport
 *   - hive_sync/host/product/upsert
 *
 * Contract version: 1 (matches HSYNC_HOST_CONTRACT_VERSION).
 */

defined( 'ABSPATH' ) || exit;

/**
 * Resolve external taxonomy name → existing or newly created term_id.
 *
 * Lookup by slug first (deterministic), then by name (case-insensitive).
 * Auto-creates when missing using the catalog manager so categories /
 * brands generated by an import inherit the same hooks the manual UI
 * uses.
 */
add_filter( 'hive_sync/host/taxonomy/resolve', function ( $term_id, string $taxonomy, string $name, array $context = [] ) {
    if ( $term_id ) return $term_id;
    if ( $name === '' ) return null;
    if ( ! taxonomy_exists( $taxonomy ) ) return null;

    $slug = sanitize_title( $name );
    $by_slug = $slug !== '' ? get_term_by( 'slug', $slug, $taxonomy ) : false;
    if ( $by_slug instanceof WP_Term ) return (int) $by_slug->term_id;

    $by_name = get_term_by( 'name', $name, $taxonomy );
    if ( $by_name instanceof WP_Term ) return (int) $by_name->term_id;

    if ( function_exists( 'rp_cm_create_category' ) ) {
        $created = rp_cm_create_category( $name, 0, $slug, $taxonomy );
        if ( is_int( $created ) && $created > 0 ) return $created;
    } else {
        $inserted = wp_insert_term( $name, $taxonomy, [ 'slug' => $slug ] );
        if ( is_array( $inserted ) && ! empty( $inserted['term_id'] ) ) {
            return (int) $inserted['term_id'];
        }
    }

    return null;
}, 10, 4 );

/**
 * Forward provenance writes to the conflict engine.
 */
add_action( 'hive_sync/host/conflict/record', function ( int $product_id, string $source, array $field_changes, array $context = [] ) {
    if ( ! function_exists( 'gh_conflict_record_source' ) ) return;
    // Hive Sync passes field_changes; gh_conflict_record_source expects
    // slice_owners. The contract aligns: keys are slice names, values are
    // source ids. Pass through verbatim.
    gh_conflict_record_source( $product_id, $source, $field_changes );
}, 10, 4 );

/**
 * Ask the conflict engine which slices an incoming write may touch.
 */
add_filter( 'hive_sync/host/conflict/resolve', function ( $resolved, int $product_id, array $incoming, string $source_id ) {
    if ( $resolved !== null ) return $resolved;
    if ( ! function_exists( 'gh_conflict_resolve' ) ) return null;
    return gh_conflict_resolve( $product_id, $incoming, $source_id );
}, 10, 4 );

/**
 * Resolve a Hive Sync Selection (Filter mode) into a list of WC product ids.
 * The Selection object is opaque to the host; we only consume its
 * `mode` and `filter` properties.
 */
add_filter( 'hive_sync/host/selection/resolve', function ( $ids, $selection ) {
    if ( $ids !== null ) return $ids;
    if ( ! is_object( $selection ) ) return null;
    if ( ! function_exists( 'gh_filter_product_ids' ) ) return null;

    $mode   = isset( $selection->mode ) && is_object( $selection->mode ) ? $selection->mode->value : '';
    $filter = isset( $selection->filter ) && is_array( $selection->filter ) ? $selection->filter : [];

    if ( $mode === 'filter' ) {
        $resolved = gh_filter_product_ids( $filter );
        return is_array( $resolved ) ? array_values( array_map( 'intval', $resolved ) ) : [];
    }

    // 'all' mode is intentionally unsupported here — each Source resolves
    // its own universe in phase 3. Returning null means Hive Sync's
    // PipelineExecutor uses its empty fallback.
    return null;
}, 10, 2 );
