<?php
/**
 * Hive Sync host bridge.
 *
 * Binds the Hive Sync host adapter contract (filters/actions defined in
 * the Hive Sync plugin) to the Golden Hive functions that already exist.
 * Purely additive: if Hive Sync is not installed nothing here ever runs;
 * if Hive Sync is installed but nothing calls the helpers, this file is
 * inert.
 *
 * Bound (phase 2):
 *   - hive_sync/host/taxonomy/resolve   → WP get_term_by + rp_cm_create_category
 *   - hive_sync/host/conflict/record    → gh_conflict_record_source
 *   - hive_sync/host/conflict/resolve   → gh_conflict_resolve
 *   - hive_sync/host/selection/resolve  → gh_filter_product_ids (Filter mode)
 *
 * Bound (phase 3):
 *   - hive_sync/host/media/preimport       → media_sideload_image (single-URL path)
 *   - hive_sync/host/product/upsert        → gh_create_simple_product / wc fallback
 *   - hive_sync/host/source/gs/fetch       → rp_rc_gs_fetch + transform
 *   - hive_sync/host/source/gs/diff        → rp_rc_gs_diff
 *   - hive_sync/host/source/gs/materialize → rp_rc_gs_create_product / _update_product
 *
 * Contract version: 1 (matches HSYNC_HOST_CONTRACT_VERSION).
 */

defined( 'ABSPATH' ) || exit;

/**
 * Resolve external taxonomy name → existing or newly created term_id.
 *
 * Lookup by slug first (deterministic), then by name (case-insensitive).
 * Auto-creates when missing using the catalog manager so categories /
 * brands generated by an import inherit the same hooks the manual UI
 * uses.
 */
add_filter( 'hive_sync/host/taxonomy/resolve', function ( $term_id, string $taxonomy, string $name, array $context = [] ) {
    if ( $term_id ) return $term_id;
    if ( $name === '' ) return null;
    if ( ! taxonomy_exists( $taxonomy ) ) return null;

    $slug = sanitize_title( $name );
    $by_slug = $slug !== '' ? get_term_by( 'slug', $slug, $taxonomy ) : false;
    if ( $by_slug instanceof WP_Term ) return (int) $by_slug->term_id;

    $by_name = get_term_by( 'name', $name, $taxonomy );
    if ( $by_name instanceof WP_Term ) return (int) $by_name->term_id;

    // Create the missing term. IMPORTANT: only delegate to
    // rp_cm_create_category() for the hierarchical catalog taxonomies it
    // actually supports. That helper runs its $taxonomy argument through
    // rp_cm_normalize_taxonomy(), which silently coerces ANYTHING that
    // isn't product_cat/product_brand down to product_cat. Routing an
    // attribute taxonomy (e.g. pa_model, whose value here is the full
    // product name) through it would therefore mint a bogus product_cat
    // term per product — 1:1 empty "model" categories that pollute the
    // category widgets. Attribute (pa_*) and tag terms must be inserted
    // into their real taxonomy instead.
    $is_catalog_tax = in_array( $taxonomy, [ 'product_cat', 'product_brand' ], true );
    if ( $is_catalog_tax && function_exists( 'rp_cm_create_category' ) ) {
        $created = rp_cm_create_category( $name, 0, $slug, $taxonomy );
        return ( is_int( $created ) && $created > 0 ) ? $created : null;
    }

    $inserted = wp_insert_term( $name, $taxonomy, $slug !== '' ? [ 'slug' => $slug ] : [] );
    if ( is_array( $inserted ) && ! empty( $inserted['term_id'] ) ) {
        return (int) $inserted['term_id'];
    }

    return null;
}, 10, 4 );

/**
 * Forward provenance writes to the conflict engine.
 */
add_action( 'hive_sync/host/conflict/record', function ( int $product_id, string $source, array $field_changes, array $context = [] ) {
    if ( ! function_exists( 'gh_conflict_record_source' ) ) return;
    // Hive Sync passes field_changes; gh_conflict_record_source expects
    // slice_owners. The contract aligns: keys are slice names, values are
    // source ids. Pass through verbatim.
    gh_conflict_record_source( $product_id, $source, $field_changes );
}, 10, 4 );

/**
 * Ask the conflict engine which slices an incoming write may touch.
 */
add_filter( 'hive_sync/host/conflict/resolve', function ( $resolved, int $product_id, array $incoming, string $source_id ) {
    if ( $resolved !== null ) return $resolved;
    if ( ! function_exists( 'gh_conflict_resolve' ) ) return null;
    return gh_conflict_resolve( $product_id, $incoming, $source_id );
}, 10, 4 );

/**
 * Resolve a Hive Sync Selection (Filter mode) into a list of WC product ids.
 * The Selection object is opaque to the host; we only consume its
 * `mode` and `filter` properties.
 */
add_filter( 'hive_sync/host/selection/resolve', function ( $ids, $selection ) {
    if ( $ids !== null ) return $ids;
    if ( ! is_object( $selection ) ) return null;
    if ( ! function_exists( 'gh_filter_product_ids' ) ) return null;

    $mode   = isset( $selection->mode ) && is_object( $selection->mode ) ? $selection->mode->value : '';
    $filter = isset( $selection->filter ) && is_array( $selection->filter ) ? $selection->filter : [];

    if ( $mode === 'filter' ) {
        $resolved = gh_filter_product_ids( $filter );
        return is_array( $resolved ) ? array_values( array_map( 'intval', $resolved ) ) : [];
    }

    // 'all' mode is intentionally unsupported here — each Source resolves
    // its own universe in phase 3. Returning null means Hive Sync's
    // PipelineExecutor uses its empty fallback.
    return null;
}, 10, 2 );

// ─── Phase 3 bindings ───────────────────────────────────────────────

/**
 * Batch parallel media sideload — delegates to gh_preimport_download_batch
 * (curl_multi sliding window, 8-16 concurrent). Returns map url=>attachment_id.
 * This is what the Hive Sync media.download import-rule hits for any
 * import processing > 1 image — single-URL path is the fallback.
 */
add_filter( 'hive_sync/host/media/preimport_batch', function ( $resolved, array $urls, array $context = [] ) {
    if ( $resolved !== null ) return $resolved;
    if ( ! function_exists( 'gh_preimport_download_batch' ) ) return null;
    $concurrency = max( 1, min( 32, (int) ( $context['concurrency'] ?? 10 ) ) );
    $r = gh_preimport_download_batch( $urls, $concurrency );
    // gh_preimport_download_batch returns map url => attachment_id (or
    // an array with WP_Error markers). Keep only the successful int ids.
    $out = [];
    foreach ( (array) $r as $url => $id ) {
        if ( is_int( $id ) && $id > 0 ) $out[ (string) $url ] = $id;
    }
    return $out;
}, 10, 3 );

/**
 * Single-URL media sideload. Returns the resulting attachment_id or null.
 * The high-throughput parallel path is used internally by GS materialize
 * + the new media.download import-rule batch helper above; this single
 * variant is the fallback for one-off lookups.
 */
add_filter( 'hive_sync/host/media/preimport', function ( $attachment_id, string $url, array $context = [] ) {
    if ( $attachment_id ) return $attachment_id;
    if ( $url === '' ) return null;

    if ( ! function_exists( 'media_sideload_image' ) ) {
        require_once ABSPATH . 'wp-admin/includes/media.php';
        require_once ABSPATH . 'wp-admin/includes/file.php';
        require_once ABSPATH . 'wp-admin/includes/image.php';
    }
    $attach_post_id = (int) ( $context['attach_to'] ?? 0 );
    $result = media_sideload_image( $url, $attach_post_id ?: 0, null, 'id' );
    if ( is_wp_error( $result ) ) return null;
    $id = (int) $result;
    return $id > 0 ? $id : null;
}, 10, 3 );

/**
 * Product upsert. Routes simple/variable to the existing factory; falls
 * back to a minimal WC create when the factory is not loaded (so a
 * standalone Hive Sync deployment without Golden Hive still creates
 * basic products).
 */
add_filter( 'hive_sync/host/product/upsert', function ( $product_id, array $data, array $context = [] ) {
    if ( $product_id ) return $product_id;

    $existing = (int) ( $data['_existing_id'] ?? 0 );
    $type     = (string) ( $data['type'] ?? 'simple' );

    if ( $existing > 0 ) {
        if ( ! function_exists( 'wc_get_product' ) ) return null;
        $p = wc_get_product( $existing );
        if ( ! $p instanceof WC_Product ) return null;
        if ( isset( $data['name'] ) )           $p->set_name( (string) $data['name'] );
        if ( isset( $data['regular_price'] ) )  $p->set_regular_price( (string) $data['regular_price'] );
        if ( isset( $data['sale_price'] ) )     $p->set_sale_price( (string) $data['sale_price'] );
        if ( isset( $data['stock_status'] ) )   $p->set_stock_status( (string) $data['stock_status'] );
        if ( isset( $data['stock_quantity'] ) ) {
            $p->set_manage_stock( true );
            $p->set_stock_quantity( (int) $data['stock_quantity'] );
        }
        if ( isset( $data['description'] ) )       $p->set_description( (string) $data['description'] );
        if ( isset( $data['short_description'] ) ) $p->set_short_description( (string) $data['short_description'] );
        $p->save();
        return $existing;
    }

    if ( $type === 'variable' && function_exists( 'gh_create_variable_product' ) ) {
        $id = gh_create_variable_product( $data );
        return $id > 0 ? $id : null;
    }
    if ( function_exists( 'gh_create_simple_product' ) ) {
        $id = gh_create_simple_product( $data );
        return $id > 0 ? $id : null;
    }

    if ( ! function_exists( 'wc_get_product' ) ) return null;
    $p = new WC_Product_Simple();
    if ( ! empty( $data['name'] ) )           $p->set_name( (string) $data['name'] );
    if ( ! empty( $data['sku'] ) )            $p->set_sku( (string) $data['sku'] );
    if ( isset( $data['regular_price'] ) )    $p->set_regular_price( (string) $data['regular_price'] );
    if ( isset( $data['stock_status'] ) )     $p->set_stock_status( (string) $data['stock_status'] );
    if ( isset( $data['description'] ) )      $p->set_description( (string) $data['description'] );
    $id = $p->save();
    return $id > 0 ? (int) $id : null;
}, 10, 3 );

// ─── GS source delegation ──────────────────────────────────────────

/**
 * Fetch + normalize + transform GS feed. Returns Hive-Sync-shaped
 * envelope: ['items' => [['sku','data','raw'], ...], 'stats' => [...],
 * 'warnings' => [...]].
 */
add_filter( 'hive_sync/host/source/gs/fetch', function ( $resp, array $config, array $options ) {
    if ( $resp !== null ) return $resp;
    if ( ! function_exists( 'rp_rc_gs_fetch' )
        || ! function_exists( 'rp_rc_gs_transform_all' )
        || ! function_exists( 'rp_rc_gs_normalize_hierarchical' )
        || ! function_exists( 'rp_rc_gs_normalize_flat' ) ) {
        return null;
    }

    $raw = rp_rc_gs_fetch( $config );
    if ( is_wp_error( $raw ) ) {
        return [ 'items' => [], 'warnings' => [ (string) $raw->get_error_message() ] ];
    }
    if ( ! is_array( $raw ) ) {
        return [ 'items' => [], 'warnings' => [ 'Fetch GS: risposta non array.' ] ];
    }

    $format = (string) ( $config['format'] ?? 'hierarchical' );
    $normalized = $format === 'flat'
        ? rp_rc_gs_normalize_flat( $raw )
        : rp_rc_gs_normalize_hierarchical( $raw );

    $priceMode = (string) ( $options['price_mode'] ?? 'direct' );
    $saleMult  = (float) ( $options['sale_mult'] ?? 1.3 );
    $woo       = rp_rc_gs_transform_all( $normalized, $priceMode, $saleMult );

    $items = [];
    foreach ( $woo as $i => $w ) {
        $items[] = [
            'sku'  => (string) ( $w['sku'] ?? '' ),
            'data' => $w,
            'raw'  => $normalized[ $i ] ?? [],
        ];
    }

    return [
        'items' => $items,
        'stats' => [
            'total'      => count( $items ),
            'format'     => $format,
            'price_mode' => $priceMode,
        ],
    ];
}, 10, 3 );

/**
 * GS diff: incoming items_data is an array of woo-shaped product arrays
 * (NOT FeedItem-wrapped). Returns the legacy bucketed shape verbatim.
 */
add_filter( 'hive_sync/host/source/gs/diff', function ( $resp, array $items_data ) {
    if ( $resp !== null ) return $resp;
    if ( ! function_exists( 'rp_rc_gs_diff' ) ) return null;
    return rp_rc_gs_diff( $items_data );
}, 10, 2 );

/**
 * GS materialize: route to legacy create/update by presence of
 * _existing_id (or SKU lookup fallback). When the per-item marker
 * `_gh_force_recreate` is set (injected by the runner when the
 * operator picked "Forza ricreazione"), route to the
 * recreate function instead — wipe the existing product's
 * variations + attributes + pa_* terms, then re-write the same shape
 * as a first-time create. Preserves the product ID so historical
 * orders/permalinks stay valid.
 */
add_filter( 'hive_sync/host/source/gs/materialize', function ( $resp, array $item_data, bool $dry_run, bool $sideload ) {
    if ( $resp !== null ) return $resp;
    if ( $dry_run ) return [ 'action' => 'skipped', 'id' => 0, 'reason' => 'dry_run' ];
    if ( ! function_exists( 'rp_rc_gs_create_product' ) || ! function_exists( 'rp_rc_gs_update_product' ) ) {
        return null;
    }

    $existing = (int) ( $item_data['_existing_id'] ?? 0 );
    if ( $existing === 0 && function_exists( 'wc_get_product_id_by_sku' ) && ! empty( $item_data['sku'] ) ) {
        $existing = (int) wc_get_product_id_by_sku( (string) $item_data['sku'] );
    }

    $force_recreate = ! empty( $item_data['_gh_force_recreate'] );

    if ( $existing > 0 ) {
        $item_data['_existing_id'] = $existing;
        if ( $force_recreate && function_exists( 'rp_rc_gs_force_recreate_product' ) ) {
            return rp_rc_gs_force_recreate_product( $item_data, $sideload );
        }
        return rp_rc_gs_update_product( $item_data );
    }
    return rp_rc_gs_create_product( $item_data, $sideload );
}, 10, 4 );

// ─── SF source delegation ─────────────────────────────────────────

/**
 * SF materialize: route Hive Sync's pre-transformed SF item to the
 * legacy create/update functions. Mirrors the GS pattern. The
 * incoming $item_data already has the full Woo shape (type +
 * attributes + variations + _sf_* meta) produced by
 * HiveSync\Sources\CsvSource::sfTransformToWoo.
 */
add_filter( 'hive_sync/host/source/sf/materialize', function ( $resp, array $item_data, bool $dry_run, bool $sideload ) {
    if ( $resp !== null ) return $resp;
    if ( $dry_run ) return [ 'action' => 'skipped', 'id' => 0, 'reason' => 'dry_run' ];
    if ( ! function_exists( 'gh_sf_create_product' ) || ! function_exists( 'gh_sf_update_product' ) ) {
        return null;
    }

    $existing = (int) ( $item_data['_existing_id'] ?? 0 );
    if ( $existing === 0 && function_exists( 'wc_get_product_id_by_sku' ) && ! empty( $item_data['sku'] ) ) {
        $existing = (int) wc_get_product_id_by_sku( (string) $item_data['sku'] );
    }

    $force_recreate = ! empty( $item_data['_gh_force_recreate'] );

    if ( $existing > 0 ) {
        $item_data['_existing_id'] = $existing;
        if ( $force_recreate && function_exists( 'gh_sf_force_recreate_product' ) ) {
            return gh_sf_force_recreate_product( $item_data, $sideload );
        }
        return gh_sf_update_product( $item_data );
    }
    return gh_sf_create_product( $item_data, $sideload );
}, 10, 4 );
